name: xlings-ci-archlinux

on:
  push:
    paths:
      - 'config/aur/**'
      - '.github/workflows/xlings-ci-archlinux.yml'

jobs:

  archlinux-test:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialization Environment
        run: |
          pacman -Syu --noconfirm base-devel git sudo shadow
          useradd -m admin
          useradd -m test
          usermod -aG wheel admin
          usermod -aG wheel test
          echo "admin ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/admin
          echo "test ALL=(ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/test
          chmod 0440 /etc/sudoers.d/admin
          chmod 0440 /etc/sudoers.d/test

      - name: Installation Xlings on Arch Linux
        run: |
          su admin -c """
            set -euo pipefail

            whoami
            pwd
            sudo chown -R test .
            echo ::group:: Copy Repo
              mkdir -p /tmp/build/src
              cp -Rv ./ /tmp/build/src/xlings
              cp -Rv ./config/aur/* /tmp/build
              cp -Rv ./config/aur/* /tmp/build/src
            echo ::endgroup::
            echo ::group:: Makepkg Xlings
              cd /tmp/build
              makepkg -sie --noconfirm
              cd -
            echo ::endgroup::
            echo ::group:: Package Info
              pacman -Qii xlings
              pacman -Ql xlings
            echo ::endgroup::
            echo ::group:: Xlings Init and test aur
              xlings
              xlings install nvm@aur --yes
            echo ::endgroup::
            echo ::group:: Xlings Add Test User
              xlings self config --adduser test
            echo ::endgroup::
          """

          su test -c """
            echo ::group:: Xlings Output
              xlings --version
            echo ::endgroup::
          """
      - name: XIM Test on Arch linux
        env:
          TEST_CI_AUR_NO_CONFIRM: true
        run: |
          su test -c """
            set -euo pipefail

            echo ::group:: Test XIM AUR Wrapper
              xlings install wechat@aur --yes
            echo ::endgroup::
          """
